Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np
def generate_vander_matrix(input_list, n, increasing=False):
    if increasing:
        output_matrix = np.array([x**i for x in input_list for i in range(n)]).reshape(input_list.size,n)
    else:
        output_matrix = np.array([x**(n-1-i) for x in input_list for i in range(n)]).reshape(input_list.size,n)
    
    return output_matrix

In [2]:
input_list = np.array([1,2,3,4,5])
no_col_opmat = 3
output_matrix_dec_order = generate_vander_matrix(input_list,no_col_opmat,False)
print("Vander matrix decreasing order\n" ,output_matrix_dec_order)
output_matrix_inc_order = generate_vander_matrix(input_list,no_col_opmat,True)
print("Vander matrix increasing order\n" ,output_matrix_inc_order)

Vander matrix decreasing order
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Vander matrix increasing order
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
def find_moving_average(input_list,window_size):
    moving_average = []
    for i in range(len(input_list)-window_size):
        moving_average.append(input_list[i:i+window_size].mean())
    return moving_average

In [4]:
input_list = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size = 3
moving_average = find_moving_average(input_list,window_size)

In [5]:
moving_average

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333]

In [6]:
len(moving_average)

10